artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/9686732423ae4d45b5eb37186d7f5cba/artifacts
end_time: 1774691167233
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9686732423ae4d45b5eb37186d7f5cba
run_name: Default
run_uuid: 9686732423ae4d45b5eb37186d7f5cba
source_name: ''
source_type: 4
source_version: ''
start_time: 1774691167221
status: 3
tags: []
user_id: mle-user
